### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hampsterx** [Luciferx86/PhoneSelectorPlugin#1]
hi there, nice lib but not working unfortunately.

Android 10 (oppo A71) - Google Pay Services v20.26.14

```
PlatformException(No Numbers found, null, null, null)
```

Has sim and can use other library eg https://pub.flutter-io.cn/packages/mobile_number

Any thoughts?

**Comment by Luciferx86** [comment]
Hey. Sorry for the late reply. Not sure what's causing the issue. I have tried the plugin on various devices and works just fine. 

Are you getting the PlatformException as soon as you call the method? Does the pop-up to select phone numbers appear at-least once?

**Comment by hampsterx** [comment]
no worries, popup appears briefly with spinner then dissapears.
Any ideas for debugging it? I'll try to test on some other devices. cheers~

**Comment by Luciferx86** [comment]
Hey. Again sorry for the late reply. I got the chance to test this out on some other devices and have found out that this an issue with android's native APIs. Can you test out production apps that are using this API, like swiggy

**Comment by jk-akshay-arora** [comment]
Closing since no responce.

**Comment by Luciferx86** [comment]
Closing since no response.

**Comment by Luciferx86** [comment]
Closing since no response.
