### ISSUE TITLE
Execution failed for task ':phone_selector:compileDebugKotlin'.

### ISSUE THREAD

**Issue by jisjoemathew91** [Luciferx86/PhoneSelectorPlugin#2]
D:\flutter\.pub-cache\hosted\pub.dartlang.org\phone_selector-1.0.5\android\src\main\kotlin\com\luciferx86\phone_selector\PhoneSelectorPlugin.kt: (107, 13): Null can not be a value of a non-null type MethodChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':phone_selector:compileDebugKotlin'.

**Comment by Luciferx86** [comment]
I'll be pushing an update by tomorrow with the fix. By that time, you can use V1.0.4. it is functional.

**Comment by jisjoemathew91** [comment]
thank you. its working.

**Comment by Luciferx86** [comment]
New V2.0.3 has been released which solves this issue. Closing
